<Health>:
    orientation: 'vertical'
    padding: 20
    Label:
        text: 'Welcome to Healthy!'
        font_size: 20
        text_size: self.size
    BoxLayout:
        Label:
            text: 'Username'
        Label:
            text: 'Password'
    BoxLayout:
        spacing: 5
        TextInput:
            id:username
            multiline: False
        TextInput:
            id:password
            multiline: False

